// <auto-generated />
namespace S00156762Week6.Migration.ClubsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialClubs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialClubs));
        
        string IMigrationMetadata.Id
        {
            get { return "201610190936294_InitialClubs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
